services:
  db:
    image: 'postgres:15-alpine'
    container_name: postgres_cinema
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_cinema_data:/var/lib/postgresql/data/
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: 'redis:7-alpine'
    container_name: redis_cinema
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    restart: always
    build: .
    container_name: backend_cinema
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr/src/app
      - WATCHFILES_FORCE_POLLING=true
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      mailhog:
        condition: service_started
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - cinema_network

  celery_worker:
    build: .
    container_name: celery_worker_cinema
    command: ["celery", "-A", "src.worker.celery", "worker", "--loglevel=info"]
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - redis
      - web
    networks:
      - cinema_network

  celery_beat:
    build: .
    container_name: celery_beat_cinema
    command: ["celery", "-A", "src.worker.celery", "beat", "--loglevel=info"]
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - redis
      - web
    networks:
      - cinema_network

  flower:
    build: .
    container_name: flower_cinema
    command: ["celery", "-A", "src.worker.celery", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - redis
      - celery_worker
    networks:
      - cinema_network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_cinema
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - web
      - flower
      - minio
      - mailhog
    networks:
      - cinema_network

  migrator:
    build: .
    container_name: alembic_migrator_cinema
    command: ["/bin/bash", "/usr/src/app/commands/run_migration.sh"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./commands:/usr/src/app/commands
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
    networks:
      - cinema_network

  mailhog:
    image: druidfi/mailhog:1.0.1
    container_name: mailhog_cinema
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - cinema_network

  minio:
    image: minio/minio:latest
    container_name: minio_cinema
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cinema_network

  minio_mc:
    image: minio/mc
    container_name: minio_mc_cinema
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb --ignore-existing myminio/${MINIO_BUCKET};
      mc policy set public myminio/${MINIO_BUCKET};
      exit 0;
      "
    networks:
      - cinema_network

volumes:
  postgres_cinema_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  cinema_network:
    driver: bridge
