name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Initialize Git repository on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            if [ ! -d "/home/ubuntu/online-cinema-api/.git" ]; then
              rm -rf /home/ubuntu/online-cinema-api
              git clone https://github.com/${{ github.repository }}.git /home/ubuntu/online-cinema-api
            else
              cd /home/ubuntu/online-cinema-api
              git fetch origin
              git reset --hard origin/develop
            fi
          '

      - name: Check and create directories on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'mkdir -p /home/ubuntu/online-cinema-api/nginx && \
             mkdir -p /home/ubuntu/online-cinema-api/nginx/auth && \
             mkdir -p /home/ubuntu/online-cinema-api/certbot/conf && \
             mkdir -p /home/ubuntu/online-cinema-api/certbot/www'

      - name: Set up environment variables on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "echo \"${{ secrets.ENV_FILE_CONTENTS }}\" > /home/ubuntu/online-cinema-api/.env.prod"

      - name: Copy Nginx configurations
        run: |
          scp -r nginx/nginx.conf ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/online-cinema-api/nginx/
          scp -r nginx/system-nginx.conf ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/online-cinema-api/nginx/
          scp -r nginx/auth/generate_htpasswd.sh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/online-cinema-api/nginx/auth/

      - name: Generate Basic Auth credentials
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "cd /home/ubuntu/online-cinema-api && \
             chmod +x nginx/auth/generate_htpasswd.sh && \
             ./nginx/auth/generate_htpasswd.sh ${{ secrets.BASIC_AUTH_USER }} ${{ secrets.BASIC_AUTH_PASS }}"

      - name: Execute Deployment Script on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'cd /home/ubuntu/online-cinema-api && bash ./commands/deploy.sh'

      - name: Setup System Nginx
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'cd /home/ubuntu/online-cinema-api && \
             sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup || true && \
             sudo cp nginx/system-nginx.conf /etc/nginx/nginx.conf && \
             sudo nginx -t && \
             sudo systemctl restart nginx && \
             sudo systemctl enable nginx'
